#!/bin/bash
#set -e

echo -e "###"
echo -e "### Please specify the name of the volume you want to use ? (i.e. hassio_data)"
read REP_USER
echo -e "###"
echo -e ">>> You choose this volume : '$REP_USER'"
echo -e ""
