#!/bin/bash
set -e

echo -e "###"
read -p "### Please specify the name of the volume you want to use ? (i.e. hassio_data)" rep_user
read REP_USER=${rep_user}
echo -e "###"
echo -e ">>> You choose this volume : '$RE_USER'"
echo -e ""
